# Generated by Django 6.0.2 on 2026-02-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_label_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='images', to='app.label'),
        ),
    ]
