# Generated by Django 6.0.2 on 2026-04-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_label_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['created_at']},
        ),
    ]
